name: Vite CI

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      VITE_URL: ${{ vars.VITE_URL }}
      VITE_BACKEND_URL: ${{ vars.VITE_BACKEND_URL }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.18.3

      - name: Install dependencies
        run: npm ci --force

      - name: Build
        run: npm run build

      - name: Deploy via SSH
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          source: "dist/"
          strip_components: 1
          rm: true
          target: ${{ secrets.SERVER_DIR }}